# Generated by Django 4.0 on 2023-11-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.TextField(choices=[('self', '個人'), ('Company', '会社')], default=1, verbose_name='所属'),
            preserve_default=False,
        ),
    ]
