# Generated by Django 4.0 on 2023-11-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.TextField(verbose_name='商品ID')),
                ('goods_title', models.TextField(verbose_name='商品名')),
                ('goods_explanation', models.TextField(verbose_name='説明')),
                ('goods_remark', models.TextField(verbose_name='備考')),
                ('goods_quality', models.TextField(verbose_name='品質')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
