# Generated by Django 4.0 on 2023-11-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_quality',
            field=models.TextField(choices=[('notuse', '未使用'), ('best', '非常に良い'), ('good', '良い'), ('nomal', '普通'), ('bat', '悪い'), ('debil', '非常に悪い')], verbose_name='品質'),
        ),
    ]
