# Generated by Django 4.0 on 2023-11-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0004_alter_goods_goods_quality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods',
            new_name='good',
        ),
    ]
