# Generated by Django 4.0 on 2023-11-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_good_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='preview',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
