# Generated by Django 4.0 on 2023-11-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_good_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='preview',
            new_name='preview1',
        ),
        migrations.AddField(
            model_name='good',
            name='preview2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='good',
            name='preview3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='good',
            name='preview4',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
