# Generated by Django 4.0 on 2023-11-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_preview_good_preview1_good_preview2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='goods_price',
            field=models.TextField(default=1, verbose_name='価格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('アニメ', 'アニメ'), ('漫画', '漫画'), ('同人誌', '同人誌'), ('CD', 'CD'), ('機械', '機械'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_quality',
            field=models.TextField(choices=[('未使用', '未使用'), ('非常に良い', '非常に良い'), ('良い', '良い'), ('普通', '普通'), ('悪い', '悪い'), ('非常に悪い', '非常に悪い')], verbose_name='品質'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_remark',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
