# Generated by Django 4.0 on 2023-11-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_good_goods_price_alter_good_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='review',
            field=models.TextField(default=1, verbose_name='レビュー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='preview1',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='写真1'),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview2',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='写真2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview3',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='写真3'),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview4',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='写真4'),
        ),
    ]
