# Generated by Django 4.0 on 2023-11-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_good_review_alter_good_preview1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='レビュー'),
        ),
    ]
